export const INSTRUCTOR_PAYOUT_REQUEST = 'INSTRUCTOR_PAYOUT_REQUEST'
export const INSTRUCTOR_PAYOUT_SUCCESS = 'INSTRUCTOR_PAYOUT_SUCCESS'
export const INSTRUCTOR_PAYOUT_FAIL = 'INSTRUCTOR_PAYOUT_FAIL'
export const INSTRUCTOR_PAYOUT_RESET = 'INSTRUCTOR_PAYOUT_RESET'
