export const INSTRUCTOR_PAYOUT_REQUEST = 'INSTRUCTOR_PAYOUT_REQUEST'
export const INSTRUCTOR_PAYOUT_SUCCESS = 'INSTRUCTOR_PAYOUT_SUCCESS'
export const INSTRUCTOR_PAYOUT_FAIL = 'INSTRUCTOR_PAYOUT_FAIL'
export const INSTRUCTOR_PAYOUT_RESET = 'INSTRUCTOR_PAYOUT_RESET'

export const INSTRUCTOR_REGISTER_REQUEST = 'INSTRUCTOR_REGISTER_REQUEST'
export const INSTRUCTOR_REGISTER_SUCCESS = 'INSTRUCTOR_REGISTER_SUCCESS'
export const INSTRUCTOR_REGISTER_FAIL = 'INSTRUCTOR_REGISTER_FAIL'
export const INSTRUCTOR_REGISTER_RESET = 'INSTRUCTOR_REGISTER_RESET'
